name: cashbuddy
description: Cashbuddy Mobile Application.


version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter 
  webview_flutter: ^3.0.4



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  flutter_lints: ^1.0.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/cashbuddyIcon.png" 
  remove_alpha_ios: true  


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/


  fonts:
    - family: DMSans
      fonts:
        - asset: fonts/DMSans-Regular.ttf

    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Medium.ttf


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
